# -*- coding: utf-8 -*-
"""Finlatics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wkaYdfEWbRHYCNzNMhQVkLBtU_E9CLPp
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv("banking_data.csv")

# Normalize column names
df.columns = df.columns.str.lower()

# ───────────── Analysis ─────────────

# 1. Marital status distribution (proxy for gender-like grouping)
marital_counts = df['marital'].value_counts()

# 2. Day of month contact distribution
day_counts = df['day'].value_counts().sort_index()

# ───────────── Visualizations ─────────────

sns.set(style="whitegrid")

# Bar plot: Marital status distribution
plt.figure(figsize=(8,4))
sns.barplot(x=marital_counts.index, y=marital_counts.values, palette='pastel')
plt.title('Distribution of Clients by Marital Status')
plt.xlabel('Marital Status')
plt.ylabel('Number of Clients')
plt.tight_layout()
plt.show()

# Bar plot: Day of month contact distribution
plt.figure(figsize=(10,4))
sns.barplot(x=day_counts.index, y=day_counts.values, palette='viridis')
plt.title('Client Contact Frequency by Day of Month')
plt.xlabel('Day of Month')
plt.ylabel('Number of Contacts')
plt.tight_layout()
plt.show()

# ───────────── Insights Summary ─────────────

print("🔍 Key Insights:")
print(f"• Most common marital status: {marital_counts.idxmax()} ({marital_counts.max()} clients)")
print(f"• Peak client contact day of month: {day_counts.idxmax()} ({day_counts.max()} contacts)")