# -*- coding: utf-8 -*-
"""headphones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hIdi7RoNMoQ1S3v6Y7Ubf1lk6pKRFEhV
"""

# Wireless Earphones Sales EDA (Simulated)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Simulate dataset
data = {
    'Order ID': range(1, 501),
    'Timestamp': pd.date_range(start='2024-01-01 08:00', periods=500, freq='3min'),
    'Age': pd.cut(pd.Series(range(18, 68)).sample(500, replace=True), bins=[17,25,35,50,100], labels=['18–25','26–35','36–50','50+']),
    'Gender': pd.Series(['Male', 'Female']).sample(500, replace=True).values,
    'Product': pd.Series(['boAt Airdopes 141', 'Realme Buds Q2', 'OnePlus Buds Z']).sample(500, replace=True).values,
    'Price': pd.Series([999, 1499, 1999, 2499, 2999]).sample(500, replace=True).values,
    'Quantity': pd.Series([1, 2]).sample(500, replace=True).values
}

df = pd.DataFrame(data)

# Extract hour of purchase
df['Hour'] = pd.to_datetime(df['Timestamp']).dt.hour

# ---- ANALYSIS ----

# 1. Sales by Hour
hour_counts = df['Hour'].value_counts().sort_index()

# 2. Sales by Price
price_counts = df.groupby('Price')['Quantity'].sum().sort_values(ascending=False)

# 3. Sales by Gender
gender_counts = df['Gender'].value_counts()

# 4. Sales by Age Group
age_counts = df['Age'].value_counts().sort_index()

# ---- VISUALIZATIONS ----

sns.set(style='whitegrid')

# Sales by Hour
plt.figure(figsize=(8,4))
sns.barplot(x=hour_counts.index, y=hour_counts.values, palette='Blues_d')
plt.title('🕒 Sales by Hour of Day')
plt.xlabel('Hour (24h)')
plt.ylabel('Number of Orders')
plt.tight_layout()
plt.show()

# Price Point Sales
plt.figure(figsize=(8,4))
sns.barplot(x=price_counts.index, y=price_counts.values, palette='Greens_d')
plt.title('💰 Sales Volume by Price')
plt.xlabel('Price (₹)')
plt.ylabel('Units Sold')
plt.tight_layout()
plt.show()

# Gender Distribution
plt.figure(figsize=(6,4))
sns.barplot(x=gender_counts.index, y=gender_counts.values, palette='Purples')
plt.title('🚻 Sales by Gender')
plt.ylabel('Number of Orders')
plt.tight_layout()
plt.show()

# Age Group
plt.figure(figsize=(6,4))
sns.barplot(x=age_counts.index.astype(str), y=age_counts.values, palette='Oranges')
plt.title('🎯 Sales by Age Group')
plt.ylabel('Number of Orders')
plt.tight_layout()
plt.show()

# ---- INSIGHT SNAPSHOT ----
print("🔍 Key Insights:")
print(f"• Peak purchase hour: {hour_counts.idxmax()}:00 with {hour_counts.max()} orders")
print(f"• Top-selling price point: ₹{price_counts.idxmax()} with {price_counts.max()} units")
print(f"• Most orders by gender: {gender_counts.idxmax()} ({gender_counts.max()} orders)")
print(f"• Top buyer age group: {age_counts.idxmax()} ({age_counts.max()} orders)")