# -*- coding: utf-8 -*-
"""TITANIC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pvt56_m0c2iTh1-V7I_7Q2jucHj8Uovk
"""

# Titanic Data Analysis Project
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

# Preview data
print(df.head())
print("\nData Info:")
print(df.info())

# Check for missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Fill missing Age with median
df['Age'].fillna(df['Age'].median(), inplace=True)

# Drop Cabin (too many missing values)
df.drop(columns='Cabin', inplace=True)

# Fill Embarked with mode
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

# Survival rate by gender
print("\nSurvival Rate by Gender:")
print(df.groupby('Sex')['Survived'].mean())

# Survival rate by class
print("\nSurvival Rate by Class:")
print(df.groupby('Pclass')['Survived'].mean())

# Plot: Survival by gender
sns.countplot(x='Survived', hue='Sex', data=df)
plt.title('Survival by Gender')
plt.show()

# Plot: Age distribution
sns.histplot(df['Age'], kde=True)
plt.title('Age Distribution')
plt.show()

# Plot: Survival by class
sns.countplot(x='Survived', hue='Pclass', data=df)
plt.title('Survival by Passenger Class')
plt.show()